set number
syntax on 
colorscheme ron
set bg=dark
set tabstop=4
set autoindent
set smartindent
set cursorline
set mouse=a
set anti
set history=1000
set scrolloff=5
set hlsearch
set incsearch
set ignorecase
set smartcase
set backup
set linebreak " set bex=DESIRED_EXTENSION 
set wildmenu
set wildmode=list:longest
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx
